name: On push main

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Update test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [repo1]

    steps:

      - name: ğŸ— Update python library and create PR
        id: pylibupdater
        uses: joanplaja/pylibupdater@v0
        with:
          library: 'django'
          new_version: '4.2'
          repository: 'joanplaja/django-poetry-example'
          branch: 'master'
          python_version: '3.8'
          pat: ${{ secrets.PAT }}